language: java
services:
- docker
before_script:
- unset _JAVA_OPTIONS
- cd finish
- chmod +x ../scripts/travisTest.sh
script: 
- ../scripts/travisTest.sh
after_script:
- logsPath=$(find . -name "console.log" | sed "s/console.log//g");
- build=$(grep "Open Liberty" $logsPath/console.log | cut -d" " -f5 | cut -d")" -f1 );
- release=$( echo "$build" | cut -d'/' -f1); 
- number=$(echo "$build" | cut -d'/' -f2); 
- ol_jv=$(grep -i "version" $logsPath/console.log);
- jv=$(printf '%s\n' "${ol_jv//$' on '/$'\n'}" | sed '2q;d'); 
- echo -e "\n"; \
  echo -e "\033[1;34m Open Liberty release:\033[0m\033[1;36m $release \033[0m \n"; \
  echo -e "\033[1;34m Open Liberty build number:\033[0m\033[1;36m $number \033[0m \n"; \
  echo -e "\033[1;34m Java version:\033[0m\033[1;36m $jv \033[0m \n";
- cd $logsPath;
- repo_name=$(echo "$TRAVIS_REPO_SLUG" | sed -e "s/\//-/g"); 
- if [ "$TRAVIS_TEST_RESULT" -eq 0 ]; then result="passed"; else result="failed"; fi; 
- serverlogsarchive="$repo_name-$TRAVIS_BUILD_NUMBER-$result.zip";
- zip -r "$serverlogsarchive" .;
- curl -H "$JFROG_TOKEN" -T "$serverlogsarchive" "https://na.artifactory.swg-devops.com/artifactory/hyc-openliberty-guides-files-generic-local/";
notifications:
  slack:
    template:
    - 'Build: <%{build_url}| %{build_number}> | Commit (<%{compare_url}|%{commit}>):
      %{commit_message}'
    - 'Repo@Branch: %{repository_slug}@%{branch}'
    - 'Author: %{author}'
    - 'Summary: %{result} in %{duration}'
    rooms:
      secure: BZsr8NN1+j6Ld6On2HAeHiX8AucdM++IXG/GEFYk9+1oIkxxIEXSYNIdosOV7gnR73k5PNFEPuEbW5eQV8aCrz5cVYSNlz3rtODgzeA4YRUDxX9bR9ai9S1iewE5IPjAZhyp3RbzW1vBGVw4yYouD6YvQixQrqF8JOEpoHnXWOGJpA+moekNWYTDTcNSwBI1lYvQYI6aPbq8VfO96A0g/eu6+3+qtwi13fOohK2zESUe7NR/heCdbX33/Evlenle3Kg+7fwA2R/cSlLflrVrZ10CN61Ne982lKe7X6DtJUb4KBbrX3gCOu7PIMLY6T/L28dthBB3gYq/rLsA8Fg77mJIFWcaSCQ+lYYLp3e1KnrFQ7TEkQntrly+gsE65wTEVRPmLTAdSrJkdZRC5FJhiuhXKadl2f8VvyMgMazDxeC25rI5+KzTYigrrmPvGEJsb8Rcm0z94dM6OoTqZlZdhvmX9pxyaMHeE8HgAtmdeVkN7bCCfrVLqzkib8sn3vk+uJgBppzl1v9rPvKFNBU49HTh25z7YCiJAP5Ef0lGiqQ22F6YJAN1AVyMN9X7lOhSNP7VVt3zSXegaSDHdbEYW86poi9M/Ku6IRvvErdvFhLdHJPa8Ap+eJRu4l3yfmTWyOh3IDx0gas4Y5mAhPBAN6HCChT7yzrYckfJmdEiHgI=
    on_success: never
    on_failure: always
branches:
  only:
  - master
  - qa
  - test-script-update
env:
  global:
  - secure: RbsO5gdO2YjQe9vLwajjEQzBCkiWafAdgW6Iih2ldSNj6EzGXn9I8P3J14DXbZXpuDVLbefeB++IXf4zYAyVH9wklBtcssmNNNJYYYDmtGnkw0ylRt/i6Rl9o80Ac9wvf/u9r7fo0g6+nOfbs1mjFs5xRI+5kNn7QlQCd7FUUiGwUisvTsNltEw97o5X0aqGk5qUKgeu4Hkk6ftNFZyftbugudUCRftu8GzwmYDvoACs2FeKvaGQk3O/vEFQ26rvNizS6Xq4n7YSNCY3htgfOZ35Fhpj81nz9Hwj1nphLRJKaQmtx3z9apPDzAfjxrXykvYD36Ya1CAgupt3Xf5VZQGsaNEwrXe2XIDhMecZS1n+DXcWBGVxk6VBw7mYuuxWnIBY8z77aOwfViNcvuVP2HeD2mbU/oHVwWxl0tW0gE8+/ZE08bcn1E3IQJKl7FT7XeSgavFNBUMsLo06m7YJ1/DFX05uHf4DF4pWYFgsjnQKrQL4am9JS7x9G/tGJg0pO6uH3Sq1BbdBcOR+dur0LoueaAQQHNjPBqFkBQK6ObH6LMdFKZpmHsm4uDcaoKDWBs0Vt6zuYwmcg5B4MsABAD9IqoXYo14yCwATb7O4MKXxyrIBAR9XyHDsee/lz1r9k/+QzvxM4QeAE0Y26+hIJEKFFOEKUmX2fi6A6+PbHZM=
  - secure: SYv0L8aN5lARfjF68hzHzbfQxA9g0sSKzfXPrZdP89ySLlURsjNBLxLz/3Qy7i/cv/M7GYCd1w+mwvvE3e7nbPVwMXYn3kdGQHK0yi7JqkZCja32I2BHQqIO2tAnTlXCdZxMyVYYSyVhcQGHoqbOBfiWZXmpD9pXDkyVLvlbLMXiZqq+PbXxfS1SppWtesKI39QQ9vMe+DKgqkyg0duA15fF+dqwICqSkgJcai6rq6ooA+9PlYBtWQf7XqP2zMCzS2fcKcFKdX0fwDkxwGmrXKz3hmdYy3vUcs86/J44IMd6LEGND9JpFuwpY6hOuxy020JcOvqGUvNENLO1BeES96s4GlNrISEdqYUGp8+7+vtGuYWJuCvoic9lwEGYwsZPQdqp8JC8D0E6QzDc6pUtByvCagx+voNjk/P9A7/U/DNgQu6Q9U4GdmYEVzKfzeLqa40LR524Vi6/226Den5mr50o9RWinT355uxyC9d0v5+ekeHFHyD4nacNDLP0NnRecPmsfZabfu+jQ8zhbuFijJzTInqg+kCEDSF9AB9/CXrJhuVKf1Bz0dcJ4934MMZESgy6JoPC0wFpA1xNwC9JB+GwECjOsb+RIIBDXArwy65btsIWEiozT0Bve9Q8no6+aKYpB/sL8TePW0L13JMoHRZ6WggrLwUrqpV1p7+9Dk4=
